### ISSUE TITLE
Font Nirmala not supported?

### ISSUE THREAD

**Issue by XiuyeXYE** [LibrePDF/OpenPDF#613]
## Code:
```kotlin
document.add(
            Chunk(
                "नमस्ते",
                FontFactory.getFont("nirmalaui-bold", "Identity-H", false, 10F, 0, null)
            )
        )
document.close()  //error from this line

```
Exception occurs at "close" line

## Exception：
![image](https://user-images.githubusercontent.com/16207730/137578416-853f273c-a3c2-453c-b7ca-1cbb54dcf500.png)

**======================**

**Describe the bug**

**To Reproduce**
Code to reproduce the issue
1. Sample Code
2. Unit-Test

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Used Font:

**Additional context**

**Comment by zengleo** [comment]
Hi, I'd like to work on this issue for academic purposes.  Thanks!

**Comment by YourLord00** [comment]
Hi,can I get a pull request？ Is this issue still open, I want to work on this to solve the issue

**Comment by asturio** [comment]
Hi @YourLord00 , @XiuyeXYE closed the issue. I think because it is solved using FOP. Maybe there is a need to document it better. Fell free doing this :-).

**Comment by YourLord00** [comment]
You mean I still can get a pull or could you explain it to me?I am
confused:(

**Comment by YourLord00** [comment]
Can I still get a pull request since I want to study for this one?

**Comment by asturio** [comment]
Take a look at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests 

Normally, you clone the project, do some changes in your copy (probably in a separate branch), and then create a pull request. If it is good, I'll merge it.
